### 주문 조회
GET http://localhost:8080/codingTest/order


### 주문 저장
POST http://localhost:8080/codingTest/order
Content-Type: application/json

{
  "orderId": "0009",
  "productName": "카페테리아",
  "options": "",
  "tableNo": 3,
  "quantity": 1,
  "orderDate": "2023-08-01",
  "orderTime": "20:11:28",
  "dateTime": "2023-08-01 20:11:28",
  "robotStatus": "",
  "dong": "120",
  "ho": "1701",
  "seq": "23071701000074",
  "ordererName": "홍길동"
}